/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */
import net.ltgt.gradle.errorprone.CheckSeverity
import net.ltgt.gradle.errorprone.errorprone

plugins {
    `java-library`
    `maven-publish`
    `jacoco`
    alias(libs.plugins.errorprone)
    alias(libs.plugins.spotless)
}

group = "com.github.wreulicke.errorprone.logstash"

repositories {
    mavenCentral()
}

dependencies {
    compileOnly(libs.errorprone.check.api)
    errorprone(libs.errorprone.core)
    compileOnly(libs.auto.service)
    annotationProcessor(libs.auto.service)

    testRuntimeOnly(libs.junit.jupiter.engine)

    testImplementation(libs.junit.jupiter.api)
    testImplementation(libs.errorprone.check.api)
    testImplementation(libs.errorprone.test.helpers)
    testRuntimeOnly(libs.slf4j.api)
    testRuntimeOnly(libs.logstash.logback.encoder)
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}


val exportsArgs = listOf(
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED",
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
)
val addExportsFile = file("${layout.buildDirectory.get()}/tmp/javadoc/add-exports.txt")
val createJavadocOptionFile by tasks.registering {
    outputs.file(addExportsFile)
    doLast {
        addExportsFile.printWriter().use { writer ->
            exportsArgs.chunked(2).forEach {
                writer.println("${it[0]}=${it[1]}")
            }
        }
    }
}


tasks {
    withType<JavaCompile> {
        options.compilerArgs.addAll(exportsArgs)
        options.errorprone.check("MemoizeConstantVisitorStateLookups", CheckSeverity.ERROR)
        options.errorprone.check("ASTHelpersSuggestions", CheckSeverity.ERROR)
        options.errorprone.check("BugPatternNaming", CheckSeverity.ERROR)
    }

    withType<Javadoc>() {
        dependsOn(createJavadocOptionFile)
        options.optionFiles(addExportsFile)
    }

    withType<Test> {
        useJUnitPlatform()
        jvmArgs = exportsArgs + listOf("--add-opens", "jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED")
        finalizedBy(named("jacocoTestReport"))
    }
}

spotless {
    java {
        googleJavaFormat()
        importOrder()
        removeUnusedImports()
        formatAnnotations()
        trimTrailingWhitespace()
        endWithNewline()
    }
    kotlinGradle {
        target("**/*.gradle.kts")
        indentWithSpaces()
    }
}

defaultTasks("spotlessApply", "build")